targets:
  $default:
    builders:
      walletkit_dart|contractBuilder:
        enabled: true
        generate_for:
          - lib/src/crypto/evm/entities/contracts/**.dart

builders:
  contractBuilder:
    import: "package:walletkit_dart/src/generator/builder.dart"
    builder_factories: ["contractBuilder"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: source