name: walletkit_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.5.0-323.0.dev

dependencies:
  bip32: ^2.0.0
  equatable: ^2.0.5
  collection: ^1.17.2
  bs58check: ^1.0.2
  dart_bech32: ^2.0.0
  convert: ^3.1.1
  pointycastle: ^3.7.3
  crypto: ^3.0.1
  http: ^1.1.0
  hive: ^2.2.3
  bip39:
    path: packages/bip39
  dotenv: ^4.2.0
  grpc: 3.2.4
  fixnum: ^1.1.0
  protobuf: ^3.1.0
  sec: ^1.1.0
  json: ^0.20.2
  macros: ^0.1.0-main.5
    

dev_dependencies:
  lints: ^4.0.0
  test: ^1.21.0
  build_runner: ^2.1.4
  hive_generator: ^2.0.0
