name: walletkit_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/nomo-app/walletkit-dart

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.0.0

dependencies:
  crypto: ^3.0.3 # dart.dev
  http: ^1.2.2 # dart.dev
  grpc: 3.2.4 # dart.dev
  fixnum: ^1.1.0 # dart.dev
  protobuf: ^3.1.0 # google.dev
  bip32: ^2.0.0
  bs58check: ^1.0.2 # TODO: Replace
  dart_bech32: ^2.0.0 # TODO: Replace
  pointycastle: ^3.7.3
  sec: ^1.1.0
  bip39:
    path: packages/bip39 # Own fork

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  dotenv: ^4.2.0
